apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-v1
  labels:
    app: myservice
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice      
  template:
    metadata:
      labels:
        app: myservice
        version: v1
    spec:     
      containers:
      - name: myservice
        image: garyr/myservice:1.0.0 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080       
---

apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:  
  selector:
    app: myservice
  ports:      
  - port: 8080
    name: http
    targetPort: 8080      
      

